export const FETCHING_DATA = 'FETCHING_DATA'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL'
export const NEW_DATA = 'NEW_DATA'
export const MARK_AS_READ = 'MARK_AS_READ'
export const MARK_AS_SPAM = 'MARK_AS_SPAM'
export const DELETE_EMAIL = 'DELETE_EMAIL'
